WIP: fix: ansible hostname
lean-delivery/ansible-role-endeca-toolsandframeworks pull request #9
Opened 2019-02-22 07:56 UTC by pavelpikta

Fix issue #8

2019-02-22 09:37 UTC, tgadiev requested changes

2019-02-22 09:37 UTC, tgadiev commented on defaults/main.yml
> +tf_hostname: "{{ ansible_hostname }}"
```suggestion
tf_hostname: "{{ ansible_fqdn }}"
```

2019-02-22 09:37 UTC, tgadiev commented on tasks/update-workbench-password.yml
> +            url: "http://{{ tf_hostname }}:{{ workbench_port }}/ifcr/login"
Only http? https not supported?

2019-02-22 09:37 UTC, tgadiev commented on tasks/update-workbench-password.yml
> +            url: "http://{{ tf_hostname }}:{{ workbench_port }}\
Only http? https not supported?

2019-02-22 10:54 UTC, pavelpikta commented on tasks/update-workbench-password.yml
> +            url: "http://{{ tf_hostname }}:{{ workbench_port }}/ifcr/login"
Need implementation to configure SSL

2019-02-22 10:54 UTC, pavelpikta commented on tasks/update-workbench-password.yml
> +            url: "http://{{ tf_hostname }}:{{ workbench_port }}\
Need implementation to configure SSL

2019-02-26 10:19 UTC, tgadiev approved these changes

2019-02-26 10:20 UTC, merged